keno input
ypark234/MSK_comparison pull request #4
Opened 2018-12-04 04:04 UTC by Relzohery

2018-12-04 04:50 UTC, ypark234 requested changes
Some minor changes to remove bias on geometry definition.

Also, comparing the figures from KENO and MCNP, I noticed these differences:
- Regulating blade is off-centered in the control shroud west room.
- +z/-z ends of reactor pool (bounding universe in KENO) seem to be different between two inputs.
- +z(and maybe -z?) end of either of safety blade or entire core seems to be different.

2018-12-04 04:50 UTC, ypark234 commented on keno/keno_input.inp
> +media 50001 1  1002 2000 -2002
I guess this(and those in following fuel pins) was meant to be `50002` instead of `50001`.

2018-12-04 04:50 UTC, ypark234 commented on keno/keno_input.inp
> +unit 12200
This is a comment to try to make numbers consistent among input files:
From the proposed model geometry, a 3x2 grid can be imagined in the core, ignoring the control shroud.
Therefore, in MCNP input, 13100 was meant to represent the fuel pin lattice(or bundle) located in row 3, column 1, which is bottom left one,
while 12200 represents the one located in row 2, column 2, which is right middle one.

I guess you switched the two numbers, 31s and 22s.

2018-12-04 04:50 UTC, ypark234 commented on keno/keno_input.inp
> +plane 4121 ypl=1 con=-25
I guess these were meant to be `zpl` instead of `ypl`.

2018-12-04 06:38 UTC, Relzohery commented
@ypark234  I addressed your comments and also there was an issue with the reflector clad but it is fixed now.

2018-12-13 21:50 UTC, ypark234 approved these changes

2018-12-13 22:32 UTC, ypark234 commented
I think this looks good. Thanks @Relzohery !
In terms of material input, let's modify them in #6.

2018-12-13 22:32 UTC, merged